### ISSUE TITLE
clear selection and redraw graphs

### ISSUE THREAD

**Issue by elma13** [rivm-syso/Analyse-Together#147]

**Comment by elma13** [comment]
Is this still the case?

**Comment by elma13** [comment]
This is for all plots, when deselecting all, then the graph stays showing the last one.

**Comment by elma13** [comment]
The graphs should be redrawn after deselecting all sensors. And maybe also after entering the Select-tab. So if you enter the visualisation tab, no sensors are selected and no plot is drawn.

**Comment by elma13** [comment]
The selection on the map is already removed, however the selection boxes are still shown. Can those also be cleared?

**Comment by elma13** [comment]
If you change your selection in the select-tab, then the previous sensors are still on the map and in the figures. If you select a sensor, then the tool crashes

**Comment by jspijker** [comment]
closed, superseded by #281
