### ISSUE TITLE
Daily and weekly plot remake in ggplot

### ISSUE THREAD

**Issue by elma13** [rivm-syso/Analyse-Together#153]
We use the openair package for this plots, that are nice plots, however it feels a bit slow. Maybe we can calculate the means with tidyverse and vreate a ggplot. Than we can consistent with the styling of the graphs too. 
Be careful with the timezone and daylight savings!!

use the function TimeAverage from openair for this

**Comment by Hendricxw** [comment]
Issue is completed. The x-axis and y-axis labels should still be included in translation eng-nl-others.
