### ISSUE TITLE
ready for production

### ISSUE THREAD

**Issue by elma13** [rivm-syso/Analyse-Together#237]
- [x] Set version number
- [x] update project list and remove large projects from list to avoid too long waiting times
- [x] include timer to delay timeout container
- [x] Add text maak groep tab
- [x] Add link to samen meten info page about the tool (including link manual)

**Comment by elma13** [comment]
@jspijker , can you check this code and the timer if it is working? I was thinking of a time delay about 15 minutes.

**Comment by jspijker** [comment]
It works for me ;-) Not sure if this will work with our proxy. Maybe just try it?

**Comment by jspijker** [comment]
closed with #238
