### ISSUE TITLE
Data selection, pres right button, not clear enough

### ISSUE THREAD

**Issue by jspijker** [rivm-syso/Analyse-Together#241]
Instructions data selection not clear enough. English instruction in last line refers to button with different name than the actual button. Also instruction is in English while selection form is in Dutch.

See https://forum.samenmeten.nl/t/feedback-samen-analyseren-tool/423/17?u=samenmeten

**Comment by elma13** [comment]
This will be changed in Issue_254. Hopefully then it is clear for the user.
