### ISSUE TITLE
Application crashes after choosing new data

### ISSUE THREAD

**Issue by jspijker** [rivm-syso/Analyse-Together#281]
When I viewed the standard dataset of Almere and then switch to new data, the applications still shows the Almere data in the map. The overview shows the newly downloaded data, but the step 1 select shows again the almere data.

Looks like the data is not properly reset. This occurs in the develop branch

**Comment by jspijker** [comment]
also related to #147 ?

**Comment by elma13** [comment]
I have an idea how to solve this, I wil work on this after the pull requests are merged

**Comment by elma13** [comment]
Add this in the server, so after loading the new data, start again at the overview page:   

# Insert change of tabs
  observeEvent(input$second_order_tabs == "Start",{
    updateTabsetPanel(inputId = "tab_figures" ,
                      selected = "Overview")
  })
