### ISSUE TITLE
Choices in select data menu must start data download

### ISSUE THREAD

**Issue by jspijker** [rivm-syso/Analyse-Together#61]
Based on the choices in the select data tab and pull down menu's. a data download should start en data must be added to the database.  Therefore we have to:

 * [x] figure out how selected values are communicated to involved modules (or new module)
 * [x] create interface with function which initiates download
 * [x] connect it al together

And while we're on it anyway, also clean up code in the database_fun file. 
See also #25

**Comment by jspijker** [comment]
Now rewrite function in https://github.com/rivm-syso/Analyse-Together/commit/8c074af636bd5eb6164f6377f6a8b443070432d1 into background function that downloads sensor + meteo + AQ ref. station. Store locations in calling function.

**Comment by jspijker** [comment]
Closed with PR #75

**Comment by elma13** [comment]
Add all functionalities inside the download button:

- download the meta data for the project/municipality
- get list of the station names
- create the queue
- download all sensor data
