### ISSUE TITLE
Put KNMI stations into prepped_data dir

### ISSUE THREAD

**Issue by jspijker** [rivm-syso/Analyse-Together#63]
knmi_stations is a vector with all the KNMI stations. This vector is created and used in separated places in our code. eg, https://github.com/rivm-syso/Analyse-Together/blob/07389633334282b03c8125e74bf7426e7df82f01/global.R#L104 and https://github.com/rivm-syso/Analyse-Together/blob/07389633334282b03c8125e74bf7426e7df82f01/funs/database_fun.R#L309

The KNMI stations should be stored in a csv in prepped data and read during start of the app

**Comment by SanneYpenburg** [comment]
Uploaded text file with KNMI stations to the prepped_data directory and changed the two lines of code on the develop branch.
