### ISSUE TITLE
Text and labels in the front end to Dutch -> make use of javascript package thing

### ISSUE THREAD

**Issue by elma13** [rivm-syso/Analyse-Together#67]
The first approach is in Dutch, however use the library to store the text. Then we can translate it later easily.

Internationalisatie: https://appsilon.github.io/shiny.i18n/ en https://github.com/Appsilon/shiny.i18n

**Comment by elma13** [comment]
Keys in the code in English, in the JSON file the translation to Dutch

**Comment by elma13** [comment]
The keys are written with a tag, in the json the whole text in dutch and english.

guidelines for the keys: 

- Information and longer text starts with "expl_"
- All elements for selection starts with "sel_"
- All titles and headers starts with "title_"
- All elements of the plots starts with "plot_"

**Comment by elma13** [comment]
It doesnot work in every function, for example the add_metadata module if you try to change the names of the columns:

 try(datatable(data_merged(),colnames = c(i18n$t("word_obs") = "n_obs", "test2" = "station_type"),

![image](https://user-images.githubusercontent.com/35841150/192287868-06b8476c-bc7d-466a-80a5-5e1903841ee5.png)

**Comment by elma13** [comment]
TODO: a nice place and flags for the different languages layout

**Comment by jspijker** [comment]
closed with PR #71
