### ISSUE TITLE
Module for component selection

### ISSUE THREAD

**Issue by SanneYpenburg** [rivm-syso/Analyse-Together#7]
The component selection module presents the available components to the user to choose from, stores the user input so it can be passed on to the communication module. 

- [x] Determine the available components (hard-coded or from external source?) and make these visible for the user. 
- [x] Determine and store the user input for further use. 

Input :

- Available components.
- Component chosen by the user.

Output:

- Component chosen by the user for the communication module.

**Comment by elma13** [comment]
To create multi-language labels it would be nice to replace the hard-coded choices to an input.
