### ISSUE TITLE
api_get_municipality_info gives error if municipality does not exist

### ISSUE THREAD

**Issue by jspijker** [rivm-syso/Analyse-Together#80]
```
Analyse-Together > api_get_municipality_info("nonexisting", conn=pool)
Error in UseMethod("rename") :
  no applicable method for 'rename' applied to an object of class
"logical"
```
Above (mis)use of api_get_municipality_info gives an hard-to-debug error in the application (probably also for api_get_project_info). If the api_* function returns a NA value (i.e. requested something non-existing), give a verbose error

**Comment by elma13** [comment]
Related tot #88 ?
